### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CrOOaSaN** [TwlghtDrgn/Operation-Destory-III#2]
[Deleted]

**Comment by CrOOaSaN** [comment]
Никнейм без больших букв, все маленькие, это гитхаб под себя изменил

**Comment by CrOOaSaN** [comment]
Напиши в E на офиц. сервере, ник: @beluga-whale:[m.....].org

**Comment by CrOOaSaN** [comment]
Гитхаб добавил заглавные буквы, в нике только маленькие

**Comment by TwlghtDrgn** [comment]
msg'd
